import hashlib
import zipfile
from pathlib import Path
from types import SimpleNamespace

import pytest

from app.fdm_exact_gcode import (
    collect_exact_gcode_artifacts,
    execute_exact_project_gcode,
    fresh_orca_env,
    normalize_generation_receipt,
    project_plate_ids,
)


PROJECT_SHA = "a" * 64


def inspection(*plate_ids: int):
    return {
        "plates": [
            {
                "plater_id": str(plate_id),
                "model_instance_count": 1,
                "model_instances": [{"object_id": str(plate_id), "instance_id": "0"}],
            }
            for plate_id in plate_ids
        ]
    }


def write_gcode(directory: Path, name: str, payload: bytes = b"; generated by Orca\nG1 X1 Y1 E1\n") -> Path:
    path = directory / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)
    return path


def write_project(project: Path):
    model = """<?xml version="1.0" encoding="UTF-8"?>
    <model xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
      <resources><object id="1" type="model"><mesh /></object></resources>
      <build><item objectid="1" printable="1" /></build>
    </model>"""
    settings = """<?xml version="1.0" encoding="UTF-8"?>
    <config>
      <plate>
        <metadata key="plater_id" value="1"/>
        <model_instance>
          <metadata key="object_id" value="1"/>
          <metadata key="instance_id" value="0"/>
          <metadata key="identify_id" value="10001"/>
        </model_instance>
      </plate>
    </config>"""
    with zipfile.ZipFile(project, "w") as archive:
        archive.writestr("3D/3dmodel.model", model)
        archive.writestr("Metadata/model_settings.config", settings)
        archive.writestr("Metadata/project_settings.config", "{}")


def generation_receipt(project: Path):
    project_sha = hashlib.sha256(project.read_bytes()).hexdigest()
    return {
        "source": {"sha256": "1" * 64},
        "printer": {"key": "ratrig_vcore3_300", "temporary_generic": False},
        "profiles": {
            "machine": {"identity": "ratrig_vcore3_300:machine", "sha256": "2" * 64},
            "process": {"identity": "ratrig_vcore3_300:pla:balanced:functional:process", "sha256": "3" * 64},
            "filament": {"identity": "ratrig_vcore3_300:pla:filament", "sha256": "4" * 64},
        },
        "engine": {"name": "OrcaSlicer", "version": "2.4.2", "service_commit": "5" * 40},
        "project": {"sha256": project_sha},
    }


def test_fresh_orca_env_replaces_generation_xdg_state(tmp_path: Path):
    generation_root = tmp_path / "generation-xdg"
    fresh_root = tmp_path / "fresh-xdg"
    base = {
        "PATH": "/usr/bin",
        "XDG_CONFIG_HOME": str(generation_root / "config"),
        "XDG_CACHE_HOME": str(generation_root / "cache"),
        "XDG_DATA_HOME": str(generation_root / "data"),
    }
    env = fresh_orca_env(base, fresh_root)
    assert env["PATH"] == "/usr/bin"
    assert env["XDG_CONFIG_HOME"] == str(fresh_root / "config")
    assert env["XDG_CACHE_HOME"] == str(fresh_root / "cache")
    assert env["XDG_DATA_HOME"] == str(fresh_root / "data")
    assert Path(env["XDG_CONFIG_HOME"]).is_dir()

    (fresh_root / "state.txt").write_text("not clean", encoding="utf-8")
    with pytest.raises(ValueError, match="must be empty"):
        fresh_orca_env(base, fresh_root)


def test_generation_receipt_binds_project_source_profiles_and_service(tmp_path: Path):
    project = tmp_path / "workpiece-production.3mf"
    write_project(project)
    receipt = generation_receipt(project)
    normalized = normalize_generation_receipt(receipt, project_sha256=receipt["project"]["sha256"])
    assert normalized["source"]["sha256"] == "1" * 64
    assert normalized["printer"]["key"] == "ratrig_vcore3_300"
    assert normalized["printer"]["temporary_generic"] is False
    assert normalized["profiles"]["machine"]["sha256"] == "2" * 64
    assert normalized["engine"]["version"] == "2.4.2"

    bad = generation_receipt(project)
    bad["project"]["sha256"] = "f" * 64
    with pytest.raises(ValueError, match="does not match the retained production 3MF"):
        normalize_generation_receipt(bad, project_sha256=receipt["project"]["sha256"])

    missing_qualification_flag = generation_receipt(project)
    del missing_qualification_flag["printer"]["temporary_generic"]
    with pytest.raises(ValueError, match="must explicitly state the temporary-generic printer flag"):
        normalize_generation_receipt(missing_qualification_flag, project_sha256=receipt["project"]["sha256"])

    mismatched_profile = generation_receipt(project)
    mismatched_profile["profiles"]["machine"]["identity"] = "other_machine:machine"
    with pytest.raises(ValueError, match="machine profile identity does not match"):
        normalize_generation_receipt(mismatched_profile, project_sha256=receipt["project"]["sha256"])


def test_execute_exact_project_uses_only_retained_3mf_and_retains_hashed_bytes(tmp_path: Path, monkeypatch):
    project = tmp_path / "workpiece-production.3mf"
    write_project(project)
    orca = tmp_path / "AppRun"
    orca.write_text("fake", encoding="utf-8")
    output = tmp_path / "exact-output"
    captured = {}

    def fake_run(command, **kwargs):
        captured["command"] = list(command)
        captured["cwd"] = kwargs["cwd"]
        captured["env"] = kwargs["env"]
        output_dir = Path(command[command.index("--outputdir") + 1])
        write_gcode(output_dir, "plate_1.gcode", b"exact retained bytes")
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr("app.fdm_exact_gcode.subprocess.run", fake_run)
    result = execute_exact_project_gcode(
        orca_bin=orca,
        project_path=project,
        output_dir=output,
        timeout_seconds=60,
        generation_receipt=generation_receipt(project),
        base_env={
            "PATH": "/usr/bin",
            "XDG_CONFIG_HOME": str(tmp_path / "generation" / "config"),
            "XDG_CACHE_HOME": str(tmp_path / "generation" / "cache"),
            "XDG_DATA_HOME": str(tmp_path / "generation" / "data"),
        },
    )

    assert str(project) == captured["command"][-1]
    assert not any(str(value).endswith(".stl") for value in captured["command"])
    assert "--load-settings" not in captured["command"]
    assert "--load-filaments" not in captured["command"]
    assert captured["cwd"] == project.parent
    fresh_root = output.with_name(f"{output.name}.xdg")
    assert captured["env"]["XDG_CONFIG_HOME"] == str(fresh_root / "config")
    assert not (output / ".xdg").exists()
    assert result["authority_state"] == "evidence_candidate"
    assert result["reopened_exact_project"] is True
    assert result["fresh_runtime_state"] is True
    assert result["plate_ids"] == [1]
    assert result["project_sha256"] == hashlib.sha256(project.read_bytes()).hexdigest()
    assert result["plates"][0]["bytes"] == b"exact retained bytes"
    assert result["plates"][0]["sha256"] == hashlib.sha256(b"exact retained bytes").hexdigest()
    assert result["plates"][0]["project_sha256"] == result["project_sha256"]
    assert result["plates"][0]["source_sha256"] == "1" * 64
    assert result["plates"][0]["profile_sha256"] == {
        "machine": "2" * 64,
        "process": "3" * 64,
        "filament": "4" * 64,
    }
    assert result["plates"][0]["service_commit"] == "5" * 40


def test_execute_exact_project_fails_if_orca_changes_retained_3mf(tmp_path: Path, monkeypatch):
    project = tmp_path / "workpiece-production.3mf"
    write_project(project)
    receipt = generation_receipt(project)
    orca = tmp_path / "AppRun"
    orca.write_text("fake", encoding="utf-8")

    def fake_run(command, **kwargs):
        with project.open("ab") as handle:
            handle.write(b"mutated")
        write_gcode(Path(command[command.index("--outputdir") + 1]), "plate_1.gcode")
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr("app.fdm_exact_gcode.subprocess.run", fake_run)
    with pytest.raises(ValueError, match="changed during exact-project slicing"):
        execute_exact_project_gcode(
            orca_bin=orca,
            project_path=project,
            output_dir=tmp_path / "exact-output",
            timeout_seconds=60,
            generation_receipt=receipt,
            base_env={"PATH": "/usr/bin"},
        )


def test_project_plate_ids_require_nonempty_unique_physical_plates():
    assert project_plate_ids(inspection(2, 1)) == (1, 2)

    with pytest.raises(ValueError, match="does not expose physical plate metadata"):
        project_plate_ids({"plates": []})

    with pytest.raises(ValueError, match="positive and unique"):
        project_plate_ids(inspection(1, 1))

    empty = inspection(1)
    empty["plates"][0]["model_instance_count"] = 0
    with pytest.raises(ValueError, match="no proven physical instances"):
        project_plate_ids(empty)


def test_collect_exact_gcode_maps_canonical_orca_filenames_to_3mf_plate_ids(tmp_path: Path):
    write_gcode(tmp_path, "plate_2.gcode", b"plate two")
    write_gcode(tmp_path, "plate_1.gcode", b"plate one")

    artifacts = collect_exact_gcode_artifacts(
        tmp_path,
        project_inspection=inspection(1, 2),
        project_sha256=PROJECT_SHA,
    )

    assert [artifact["plate_id"] for artifact in artifacts] == [1, 2]
    assert [artifact["filename"] for artifact in artifacts] == ["plate_1.gcode", "plate_2.gcode"]
    assert artifacts[0]["bytes"] == b"plate one"
    assert artifacts[0]["byte_count"] == len(b"plate one")
    assert artifacts[0]["sha256"] == hashlib.sha256(b"plate one").hexdigest()
    assert artifacts[0]["project_sha256"] == PROJECT_SHA


def test_collect_exact_gcode_fails_closed_on_missing_plate(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode")
    with pytest.raises(ValueError, match="plate set mismatch"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1, 2),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_fails_closed_on_unexpected_plate(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode")
    write_gcode(tmp_path, "plate_2.gcode")
    with pytest.raises(ValueError, match="unexpected physical plate 2"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_fails_closed_on_noncanonical_filename(tmp_path: Path):
    write_gcode(tmp_path, "workpiece-production.gcode")
    with pytest.raises(ValueError, match="Unexpected Orca G-code filename"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_rejects_nested_output(tmp_path: Path):
    write_gcode(tmp_path / "nested", "plate_1.gcode", b"nested")
    with pytest.raises(ValueError, match="outside the exact output directory root"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_fails_closed_on_empty_output(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode", b"")
    with pytest.raises(ValueError, match="empty G-code artifact"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_requires_valid_project_digest(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode")
    with pytest.raises(ValueError, match="3MF SHA-256 is invalid"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256="not-a-digest",
        )
