import hashlib
from pathlib import Path

import pytest

from app.fdm_exact_gcode import collect_exact_gcode_artifacts, fresh_orca_env, project_plate_ids


PROJECT_SHA = "a" * 64


def inspection(*plate_ids: int):
    return {
        "plates": [
            {
                "plater_id": str(plate_id),
                "model_instance_count": 1,
                "model_instances": [{"object_id": str(plate_id), "instance_id": "0"}],
            }
            for plate_id in plate_ids
        ]
    }


def write_gcode(directory: Path, name: str, payload: bytes = b"; generated by Orca\nG1 X1 Y1 E1\n") -> Path:
    path = directory / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)
    return path


def test_fresh_orca_env_replaces_generation_xdg_state(tmp_path: Path):
    generation_root = tmp_path / "generation-xdg"
    fresh_root = tmp_path / "fresh-xdg"
    base = {
        "PATH": "/usr/bin",
        "XDG_CONFIG_HOME": str(generation_root / "config"),
        "XDG_CACHE_HOME": str(generation_root / "cache"),
        "XDG_DATA_HOME": str(generation_root / "data"),
    }
    env = fresh_orca_env(base, fresh_root)
    assert env["PATH"] == "/usr/bin"
    assert env["XDG_CONFIG_HOME"] == str(fresh_root / "config")
    assert env["XDG_CACHE_HOME"] == str(fresh_root / "cache")
    assert env["XDG_DATA_HOME"] == str(fresh_root / "data")
    assert Path(env["XDG_CONFIG_HOME"]).is_dir()

    (fresh_root / "state.txt").write_text("not clean", encoding="utf-8")
    with pytest.raises(ValueError, match="must be empty"):
        fresh_orca_env(base, fresh_root)


def test_project_plate_ids_require_nonempty_unique_physical_plates():
    assert project_plate_ids(inspection(2, 1)) == (1, 2)

    with pytest.raises(ValueError, match="does not expose physical plate metadata"):
        project_plate_ids({"plates": []})

    with pytest.raises(ValueError, match="positive and unique"):
        project_plate_ids(inspection(1, 1))

    empty = inspection(1)
    empty["plates"][0]["model_instance_count"] = 0
    with pytest.raises(ValueError, match="no proven physical instances"):
        project_plate_ids(empty)


def test_collect_exact_gcode_maps_canonical_orca_filenames_to_3mf_plate_ids(tmp_path: Path):
    write_gcode(tmp_path, "plate_2.gcode", b"plate two")
    write_gcode(tmp_path, "plate_1.gcode", b"plate one")

    artifacts = collect_exact_gcode_artifacts(
        tmp_path,
        project_inspection=inspection(1, 2),
        project_sha256=PROJECT_SHA,
    )

    assert [artifact["plate_id"] for artifact in artifacts] == [1, 2]
    assert [artifact["filename"] for artifact in artifacts] == ["plate_1.gcode", "plate_2.gcode"]
    assert artifacts[0]["bytes"] == b"plate one"
    assert artifacts[0]["byte_count"] == len(b"plate one")
    assert artifacts[0]["sha256"] == hashlib.sha256(b"plate one").hexdigest()
    assert artifacts[0]["project_sha256"] == PROJECT_SHA


def test_collect_exact_gcode_fails_closed_on_missing_plate(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode")
    with pytest.raises(ValueError, match="plate set mismatch"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1, 2),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_fails_closed_on_unexpected_plate(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode")
    write_gcode(tmp_path, "plate_2.gcode")
    with pytest.raises(ValueError, match="unexpected physical plate 2"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_fails_closed_on_noncanonical_filename(tmp_path: Path):
    write_gcode(tmp_path, "workpiece-production.gcode")
    with pytest.raises(ValueError, match="Unexpected Orca G-code filename"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_fails_closed_on_duplicate_plate_output(tmp_path: Path):
    write_gcode(tmp_path / "a", "plate_1.gcode", b"first")
    write_gcode(tmp_path / "b", "plate_1.gcode", b"second")
    with pytest.raises(ValueError, match="more than one G-code artifact"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_fails_closed_on_empty_output(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode", b"")
    with pytest.raises(ValueError, match="empty G-code artifact"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256=PROJECT_SHA,
        )


def test_collect_exact_gcode_requires_valid_project_digest(tmp_path: Path):
    write_gcode(tmp_path, "plate_1.gcode")
    with pytest.raises(ValueError, match="3MF SHA-256 is invalid"):
        collect_exact_gcode_artifacts(
            tmp_path,
            project_inspection=inspection(1),
            project_sha256="not-a-digest",
        )
